### ISSUE TITLE
Warnings during a start-up script

### ISSUE THREAD

**Issue by ddebernardy** [jeremyevans/home_run#29]
I've run `home_run --install` after toying around and creating a sinatra-based hello world app. I'm getting the following warnings when I restart the app (this is on a MacOS laptop):

```
DB:~/Sites/rubyapp $ cat scripts/thin/thin.sh
#!/bin/sh

prefix=/opt/local

case $1 in
  start  )  [ -x /opt/local/bin/thin ] && \
            /opt/local/bin/thin start -C /Users/denis/Sites/rubyapp/config/thin.yml #> /dev/null
            ;;
  stop   )  [ -x /opt/local/bin/thin ] && \
            /opt/local/bin/thin stop -C /Users/denis/Sites/rubyapp/config/thin.yml #> /dev/null
            ;;
  restart)  [ -x /opt/local/bin/thin ] && \
            /opt/local/bin/thin restart -C /Users/denis/Sites/rubyapp/config/thin.yml #> /dev/null
            ;;
  *      )  echo "$0: unknown argument: $1";;
esac

DB:~/Sites/rubyapp $ sudo ./scripts/thin/thin.sh restart
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:25: warning: already initialized constant STYLE
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:34: warning: already initialized constant MONTHS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:41: warning: already initialized constant DAYS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:47: warning: already initialized constant ABBR_MONTHS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:54: warning: already initialized constant ABBR_DAYS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:60: warning: already initialized constant ZONES
```

I dutifully sought to conditionally initialize them and offer a patch, that would go something like:

```
STYLE = {} if STYLE.nil?
...
STYLE.merge!({:dot=>:mdy, :slash=>:mdy})
```

Sadly though, one of the hashes seems to be frozen and my ruby skills are so that I've absolutely no idea of how to unfreeze it in order to work around the warning.

**Comment by jeremyevans** [comment]
Those errors indicate that home_run's date/format.rb file is getting loaded twice.  I'd add a puts caller to the top of the file and then rerun.  You should get two separate backtraces, one for each time it was loaded.  If you can post both backtraces, it will be possible to determine why it is getting loaded twice.

If this only happens on restart, it may be do to something special thin does when it restarts.

BTW, you can't unfreeze things in ruby without nefarious things like evil.rb or evilr.

Since you are already using ruby 1.9, you may want to jump to ruby-head, where the stdlib date class is almost as fast as home_run.

**Comment by ddebernardy** [comment]
After adding the `puts caller`, here's the full trace:

```
DB:~/Sites/rubyapp $ sudo ./scripts/thin/thin.sh restart

Caller:

/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:17:in `<class:Date>'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:6:in `<top (required)>'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/1.9.1/time.rb:39:in `<top (required)>'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/thin-1.2.11/lib/thin.rb:4:in `<top (required)>'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/thin-1.2.11/bin/thin:5:in `<top (required)>'
/opt/local/bin/thin:19:in `load'
/opt/local/bin/thin:19:in `<main>'


/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:33: warning: already initialized constant STYLE
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:42: warning: already initialized constant MONTHS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:49: warning: already initialized constant DAYS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:55: warning: already initialized constant ABBR_MONTHS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:62: warning: already initialized constant ABBR_DAYS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:68: warning: already initialized constant ZONES
Stopping server on 0.0.0.0:5000 ... 

Caller:

/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:17:in `<class:Date>'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:6:in `<top (required)>'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/1.9.1/time.rb:39:in `<top (required)>'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/thin-1.2.11/lib/thin.rb:4:in `<top (required)>'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/thin-1.2.11/bin/thin:5:in `<top (required)>'
/opt/local/bin/thin:19:in `load'
/opt/local/bin/thin:19:in `<main>'


Sending QUIT signal to process 740 ... 
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:33: warning: already initialized constant STYLE
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:42: warning: already initialized constant MONTHS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:49: warning: already initialized constant DAYS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:55: warning: already initialized constant ABBR_MONTHS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:62: warning: already initialized constant ABBR_DAYS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:68: warning: already initialized constant ZONES
Starting server on 0.0.0.0:5000 ... 

Caller:

/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:17:in `<class:Date>'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:6:in `<top (required)>'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/1.9.1/time.rb:39:in `<top (required)>'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/thin-1.2.11/lib/thin.rb:4:in `<top (required)>'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/thin-1.2.11/bin/thin:5:in `<top (required)>'
/opt/local/bin/thin:19:in `load'
/opt/local/bin/thin:19:in `<main>'


/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:33: warning: already initialized constant STYLE
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:42: warning: already initialized constant MONTHS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:49: warning: already initialized constant DAYS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:55: warning: already initialized constant ABBR_MONTHS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:62: warning: already initialized constant ABBR_DAYS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:68: warning: already initialized constant ZONES
```

**Comment by ddebernardy** [comment]
Looked a bit deeper in it. Thin is apparently calling:

```
require 'time'
```

rubygems then proceeds with:

```
  def require path
    if Gem.unresolved_deps.empty? or Gem.loaded_path? path then
      gem_original_require path
    else
      # ...
```

And the date class does:

```
require 'date' unless defined?(Date::MONTHNAMES)

class Date
  # Holds some constants used by the pure ruby parsing code.
  #
  # The STYLE constant (a hash) allows the user to modify the parsing
  # of DD/DD/DD and DD.DD.DD dates.  For DD/DD/DD dates, you
  # can set the :slash entry to :mdy (month/day/year,
  # :dmy (day/month/year), or :ymd (year/month/day).  The same
  # can be done for DD.DD.DD dates using the :dot entry.  Example:
  #
  #   Date::Format::STYLE[:slash] = :mdy
  #   Date::Format::STYLE[:dot] = :dmy
  module Format
```

It looks clearly related to thin, though:

```

DB:~/Sites/rubyapp $ sudo /opt/local/bin/thin stop
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:25: warning: already initialized constant STYLE
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:34: warning: already initialized constant MONTHS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:41: warning: already initialized constant DAYS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:47: warning: already initialized constant ABBR_MONTHS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:54: warning: already initialized constant ABBR_DAYS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:60: warning: already initialized constant ZONES
Can't stop process, no PID found in tmp/pids/thin.pid
DB:~/Sites/rubyapp $ sudo /opt/local/bin/thin -C /Users/denis/Sites/rubyapp/config/thin.yml stop
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:25: warning: already initialized constant STYLE
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:34: warning: already initialized constant MONTHS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:41: warning: already initialized constant DAYS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:47: warning: already initialized constant ABBR_MONTHS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:54: warning: already initialized constant ABBR_DAYS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:60: warning: already initialized constant ZONES
Stopping server on 0.0.0.0:5000 ... 
Can't stop process, no PID found in tmp/thin/thin.5000.pid
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:25: warning: already initialized constant STYLE
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:34: warning: already initialized constant MONTHS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:41: warning: already initialized constant DAYS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:47: warning: already initialized constant ABBR_MONTHS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:54: warning: already initialized constant ABBR_DAYS
/opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:60: warning: already initialized constant ZONES
```

I'll open a ticket on their end with a reference to this one.

**Comment by ddebernardy** [comment]
It might also be an issue in rubygems, actually. After uninstalling home_run, I get:

```

DB:~/Sites/rubyapp $ sudo /opt/local/bin/thin stop
/opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': no such file to load -- date_ext (LoadError)
    from /opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/local/lib/ruby1.9/site_ruby/1.9.1/date.rb:2:in `<top (required)>'
    from /opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/local/lib/ruby1.9/site_ruby/1.9.1/date/format.rb:4:in `<top (required)>'
    from /opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/local/lib/ruby1.9/1.9.1/time.rb:39:in `<top (required)>'
    from /opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/thin-1.2.11/lib/thin.rb:4:in `<top (required)>'
    from /opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/local/lib/ruby1.9/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/thin-1.2.11/bin/thin:5:in `<top (required)>'
    from /opt/local/bin/thin:19:in `load'
    from /opt/local/bin/thin:19:in `<main>'
```

And the date folder is still around.

---

Edit: just realized that I maybe should have run `home_run --uninstall` first. Oh well... ruby's recompiling with a clean slate...
