### ISSUE TITLE
home_run rails: ruby Date gets loaded first?

### ISSUE THREAD

**Issue by jaylevitt** [jeremyevans/home_run#39]
Rails 3.1.1rc2, Ruby 1.9.2-p290 with railsexpress patches, OS X 10.6.8:

```
home_run rails c profile
/Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/date/format.rb:8: warning: already initialized constant MONTHS
/Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/date/format.rb:14: warning: already initialized constant DAYS
/Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/date/format.rb:19: warning: already initialized constant ABBR_MONTHS
/Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/date/format.rb:25: warning: already initialized constant ABBR_DAYS
/Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/date/format.rb:30: warning: already initialized constant ZONES
/Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/date.rb:236: warning: already initialized constant MONTHNAMES
/Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/date.rb:242: warning: already initialized constant DAYNAMES
/Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/date.rb:245: warning: already initialized constant ABBR_MONTHNAMES
/Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/date.rb:249: warning: already initialized constant ABBR_DAYNAMES
/Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/date.rb:301: warning: already initialized constant ITALY
/Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/date.rb:305: warning: already initialized constant ENGLAND
/Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/date.rb:309: warning: already initialized constant JULIAN
/Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/date.rb:313: warning: already initialized constant GREGORIAN
/Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/date.rb:1846:in `private_class_method': undefined method `today' for class `Class' (NameError)
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/date.rb:1846:in `<class:DateTime>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/date.rb:1832:in `<top (required)>'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/arel-2.2.1/lib/arel/visitors/to_sql.rb:2:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/arel-2.2.1/lib/arel/visitors/to_sql.rb:2:in `<top (required)>'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/arel-2.2.1/lib/arel/visitors.rb:3:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/arel-2.2.1/lib/arel/visitors.rb:3:in `<top (required)>'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/arel-2.2.1/lib/arel.rb:19:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/arel-2.2.1/lib/arel.rb:19:in `<top (required)>'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1.rc2/lib/active_record.rb:27:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1.rc2/lib/active_record.rb:27:in `<top (required)>'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1.rc2/lib/active_record/railtie.rb:1:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1.rc2/lib/active_record/railtie.rb:1:in `<top (required)>'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.1.rc2/lib/rails/all.rb:12:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.1.rc2/lib/rails/all.rb:12:in `block in <top (required)>'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.1.rc2/lib/rails/all.rb:5:in `each'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.1.rc2/lib/rails/all.rb:5:in `<top (required)>'
    from /Users/jay/src/tiptap/2t2/config/application.rb:3:in `require'
    from /Users/jay/src/tiptap/2t2/config/application.rb:3:in `<top (required)>'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.1.rc2/lib/rails/commands.rb:38:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.1.rc2/lib/rails/commands.rb:38:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by jeremyevans** [comment]
What does your bundler Gemfile look like?  If you don't have `gem 'home_run', :require=>'date'` in it, you may run into problems.  You can also try using home_run --install instead of the home_run binary.

**Comment by jaylevitt** [comment]
Ah, yes, it was the Gemfile - I didn't realize that was necessary if I was running home_run from the command line. Thanks!
