### ISSUE TITLE
uninitialized constant Date::ZONES

### ISSUE THREAD

**Issue by ankopainting** [jeremyevans/home_run#7]
I installed home_run with ree and installed yard version 0.8.0
when i run
yard server
I get
/home/nick/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/site_ruby/1.8/date/format.rb:60: uninitialized constant Date::ZONES (NameError)
        from /home/nick/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /home/nick/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from /home/nick/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/parsedate.rb:22
        from /home/nick/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /home/nick/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from /home/nick/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/time.rb:43
        from /home/nick/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /home/nick/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from /home/nick/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/open-uri.rb:3
        from /home/nick/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /home/nick/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from /home/nick/.rvm/gems/ree-1.8.7-2010.02/gems/yard-0.6.0/lib/yard/cli/diff.rb:3
        from /home/nick/.rvm/gems/ree-1.8.7-2010.02/gems/yard-0.6.0/lib/yard/cli/command_parser.rb:34
        from /home/nick/.rvm/gems/ree-1.8.7-2010.02/gems/yard-0.6.0/bin/yard:4
        from /home/nick/.rvm/gems/ree-1.8.7-2010.02/bin/yard:19:in `load'
        from /home/nick/.rvm/gems/ree-1.8.7-2010.02/bin/yard:19

running
home_run --uninstall
fixes the issue.

**Comment by ankopainting** [comment]
this was already fixed on master.
